providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
  file:
    directory: "/dyn-config/"
    watch: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

log:
  level: INFO